(defun comment-or-uncomment-line-or-region ()
  (interactive)
  (if (region-active-p)
      (comment-or-uncomment-region (region-beginning) (region-end))
    (comment-or-uncomment-region (point) (line-end-position))))
(global-set-key (kbd "C-;") 'comment-or-uncomment-line-or-region)
